language: python
cache: pip
dist: xenial
python:
    - '2.7'
    - '3.5'
    - '3.6'
    - '3.7'
    - '3.8'
    - pypy
    - pypy3
install:
    - pip install codecov tox
script:
    - tox -e py-toml,py-notoml
after_success:
    - codecov
